R -e "install.packages('BMTME', repos='http://cran.rstudio.com/')"
R -e "install.packages('plyr', repos='http://cran.rstudio.com/')"
R -e "install.packages('tidyr', repos='http://cran.rstudio.com/')"
R -e "install.packages('dplyr', repos='http://cran.rstudio.com/')"
R -e "install.packages('tfruns', repos='http://cran.rstudio.com/')"
R -e "install.packages('reshape2', repos='http://cran.rstudio.com/')"
R -e "install.packages('readxl', repos='http://cran.rstudio.com/')"
R -e "install.packages('crossdes', repos='http://cran.rstudio.com/')"